### ISSUE TITLE
Java null pointer exception

### ISSUE THREAD

**Issue by ndesorden** [dfredriksen/XPlatformHTMLLabel#1]
Hi, i've your label control binded to a viewmodel property, but html is retreive from a rest service at OnAppearing method so binding is done in this method.

protected override async void OnAppearing()
{
if (!_isDataLoaded)
  await MethodToCalltoServiceAndBinding;

 base.OnAppearing();
} 

`<xPlatformHtmlLabel:HtmlLabel Text="{Binding Summary}"></xPlatformHtmlLabel:HtmlLabel>`

In this scenario code breaks with java null pointer exception.

It can be fixed with something like:

`Control?.SetText(FromHtml(Element.Text ?? string.Empty), TextView.BufferType.Spannable);`

Tested only in android

Thanks!

**Comment by dfredriksen** [comment]
👍
